### ISSUE TITLE
index.html　Link broken

### ISSUE THREAD

**Issue by cyoco** [terasoluna-batch/terasoluna-batch.github.io#1]
index.htmlの下記リンクが切れてます。

> サンプルアプリケーション
> ガイドラインに則った各機能の実装例です。コードを見ることで直感的に理解できます。 詳細は、 terasoluna-batch/v5-functionaltestを参照してください。

→terasoluna-batch/v5-functionaltest　の https://github.com/terasoluna-batch/v5-functionaltest

> 機能追加要望・改善要望
> TERASOLUNA Batch Framework for Java (5.x)では随時、機能追加要望および改善要望・バグ報告を受け付けております。 各GitHubリポジトリのIssuesにご報告下さい。
> 
> 開発ガイドライン
> 共通ライブラリ

→開発ガイドライン の　https://github.com/terasoluna-batch/v5-guideline/issues

また、併せてリンクが切れてる「サンプルアプリケーション（v5-functionaltest）」の
代替するサンプルあれば連携お願いします。

**Comment by btkataokatik** [comment]
ご報告ありがとうございます。返答が遅くなり申し訳ございません。  
index.htmlを修正いたしました。下記をご確認をお願いします。  
https://terasoluna-batch.github.io/

サンプルアプリケーションについては以下のようにリンク先が変更されていますので、こちらもご確認をお願い致します。

> ガイドラインに則った各機能の実装例です。コードを見ることで直感的に理解できます。 詳細は、 Macchinetta/macchinetta-batch-functionaltestを参照してください。 TERASOLUNA Batch Frameworkのサンプルアプリケーションは、OSSであるMacchinetta Batch Frameworkの成果物をそのまま利用しています。

修正が完了しましたので、クローズさせていただきます。
