### ISSUE TITLE
入力チェック処理について

### ISSUE THREAD

**Issue by deffence1776** [terasoluna-batch/terasoluna-batch.github.io#2]
下記について質問/相談です。

１意見ですので、すでに内部で同じような議論がされていれば、お手すきの時にでも教えてください。
closeのタイミングはお任せします。特に私の同意を得る必要はありません。

https://terasoluna-batch.github.io/guideline/5.1.1.RELEASE/ja/Ch06_InputValidation.html#Ch06_InputValidation_HowToUse_ErrorHandling

例外発生時にProcessorが最初から入力を処理する、というのは意識できてなかったので助かりました。

ただ、skippable-exceptionを使わず、ValidationException時にnullを返すことでフィルターするとなると、FileParse時のExceptionの場合は異常終了となると思います。項目数不足、フォーマット違いなど。

ファイル読み取りにおいてはプロパティは原則Stringでフィールド定義するなどの対策すれば項目数不足ぐらいしか考えられなくなりますが、CSVなどの場合は項目数不足もスキップしたい場合もあるかと。

この場合、似たような関心事で記述方法と記述場所が異なってしまうので、個人的には、Spring Batchのドキュメントにも書かれている委譲を使って、read時に入力データの検証と例外処理を集約したほうがシンプルになるかと思います。

また、異常終了時も、チャンクの全データを読み込んでから実行させるprocessorで異常検知させるよりreaderでやってしまった方が早いように思います。

設計書との紐づけも、データごとの前処理と本処理として整理すればそれほど問題ないかと

```
public class ValidationItemStreamReader<T> implements ItemStreamReader<T> {

	protected Validator<T> validator;

	protected ItemStreamReader<T> delegate;

	public void setDelegate(ItemStreamReader<T> delegate) {
		this.delegate = delegate;
	}

	public void setValidator(Validator<T> validator) {
		this.validator = validator;
	}

	@Override
	public void close() throws ItemStreamException {
		delegate.close();
	}

	@Override
	public void open(ExecutionContext executionContext) throws ItemStreamException {
		delegate.open(executionContext);
	}

	@Override
	public void update(ExecutionContext executionContext) throws ItemStreamException {
		delegate.update(executionContext);
	}

	/**
	 * サブクラスでオーバーライドを想定
	 */
	@Override
	public T read() throws Exception, UnexpectedInputException, ParseException, NonTransientResourceException {
		T item = null;
		try {
			item = delegate.read();
			if (null != item) {
				validator.validate(item);
				
				//対応するマスター存在チェックなど
			}
		
		} catch (ValidationException e) {
			//例外処理
			throw new SkippableException(e);
		} catch (ParseException e) {
			//例外処理
			throw new SkippableException(e);
		}

		return item;
	}
}

```

**Comment by yggd** [comment]
入力チェックをどの場所でやるかは検討していました。
リスタートなどを考えた場合、特定のデータまで読み飛ばす必要があるのですが、
ご提示していただいた方法だとSikpすべきデータまで再度検証を実行してしまうことが問題になります。
上記のように、リカバリ方法も含めて検討した結果、ガイドラインで紹介している内容になります。
