### ISSUE TITLE
チュートリアル内の軽微なTypoを見つけましたので共有いたします

### ISSUE THREAD

**Issue by yukiz** [terasoluna-batch/terasoluna-batch.github.io#3]
### Typoです.クラス名のDTOがキャメルケースになっています.

https://github.com/terasoluna-batch/terasoluna-batch.github.io/blob/7520d2a0716affab9dfda97698daec2f37cdba84/guideline/5.1.1.RELEASE/ja/Ch09_FileAccessJob.html#L1292

```
package org.terasoluna.batch.tutorial.common.dto;

public class MemberInfoDto {
```

---

### Typoです.タスクレットモデルでの実装で,component-scanのパッケージが**chunk**になっています.
https://github.com/terasoluna-batch/terasoluna-batch.github.io/blob/7520d2a0716affab9dfda97698daec2f37cdba84/guideline/5.1.1.RELEASE/ja/Ch09_FileAccessJob.html#L1396

```
 <context:component-scan base-package="org.terasoluna.batch.tutorial.fileaccess.chunk"/>
```

**Comment by btmikamiysy** [comment]
ご指摘ありがとうございます。
ご指摘いただいた内容を5.2.1.RELEASEで対応しました。

https://terasoluna-batch.github.io/guideline/5.2.1.RELEASE/ja/Ch09_FileAccessJob.html#Ch09_Impl_FileAccessJob
